apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qydj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mugw-tenant/rhtap-demo-app/hacbs-test-project-qydj@sha256:3899b636584e1208756f0a824ffe50367b60cd2d32614d0bfdc7f5700e47e80c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
